const colors = require("tailwindcss/colors");

module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      outline: {
        black: "1px solid black",
      },
      spacing: {
        7: "1.75rem",
        14: "3.5rem",
        21: "5.25rem",
        28: "7rem",
        35: "8.75rem",
        42: "10.5rem",
        49: "12.25rem",
        56: "14rem",
        63: "15.75rem",
        70: "17.5rem",
        74: "18.5rem",
        77: "19.25rem",
        84: "21rem",
        91: "22.75rem",
        98: "24.5rem",
        105: "26.25rem",
        10: "2.5rem",
        20: "5rem",
        30: "7.5rem",
        40: "10rem",
        50: "12.5rem",
        60: "15rem",
        80: "20rem",
        90: "22.5rem",
        100: "25rem",
        104: "26rem",
        107: "26.75rem",
        110: "27.5rem",
        120: "30rem",
        130: "32.5rem",
        140: "35rem",
        148: "37rem",
        150: "37.5rem",
        157: "39.25rem",
      },
      gridTemplateColumns: {
        15: "repeat(15, minmax(0, 2rem))",
        sm15: "repeat(15, minmax(0, 1.5rem))",
      },
      gridTemplateRows: {
        15: "repeat(15, minmax(0, 2rem))",
        sm15: "repeat(15, minmax(0, 1.5rem))",
      },
      gridRowStart: {
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
      },
      gridRowEnd: {
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
      },
      gridColumnStart: {
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
      },
      gridColumnEnd: {
        8: "8",
        9: "9",
        10: "10",
        11: "11",
        12: "12",
        13: "13",
        14: "14",
        15: "15",
        16: "16",
      },
      backgroundImage: {
        "safe-cell": "url(./images/safe.svg)",
        "start-red-cell": "url(./images/red-start.svg)",
        "start-green-cell": "url(./images/green-start.svg)",
        "start-blue-cell": "url(./images/blue-start.svg)",
        "start-yellow-cell": "url(./images/yellow-start.svg)",
        "end-red-cell": "url(./images/red-end.svg)",
        "end-green-cell": "url(./images/green-end.svg)",
        "end-blue-cell": "url(./images/blue-end.svg)",
        "end-yellow-cell": "url(./images/yellow-end.svg)",
        "final-red-cell": "url(./images/red-final.svg)",
        "final-green-cell": "url(./images/green-final.svg)",
        "final-blue-cell": "url(./images/blue-final.svg)",
        "final-yellow-cell": "url(./images/yellow-final.svg)",
        "arrow-red-cell": "url(./images/red-arrow.svg)",
        "arrow-green-cell": "url(./images/green-arrow.svg)",
        "arrow-blue-cell": "url(./images/blue-arrow.svg)",
        "arrow-yellow-cell": "url(./images/yellow-arrow.svg)",
      },
      rotate: {
        "-360": "-720deg",
        360: "720deg",
      },
      colors: {
        blueGray: colors.blueGray,
        antiqueWhite: "#faebd7",
        blue: colors.blue,
        green: colors.green,
        yellow: colors.yellow,
        red: colors.red,
      },
      animation: {
        dropdown: "dropdown 450ms ease-in 1",
        wiggle: "wiggle 300ms cubic-bezier(0.7, 0.01, 0.35, 1) infinite",
      },
      keyframes: {
        dropdown: {
          "0%": {
            transform: "translateY(-25%)",
          },
          "100%": {
            transform: "translateY(0)",
          },
        },
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
      },
    },
  },
  variants: {
    extend: {},
  },
};
